version: '3'

services:
  nodejs:
    #fill out the configuration here
    build:
      context: .
      # built using custom Dockerfile
      dockerfile: Dockerfile
      # tagged with custom name
    container_name: KO_Site
    # If fails or crashes, restart container and try again
    restart: unless-stopped
    networks:
      - app-network
  
  #the nginx configuration is given below
  #the website will run on localhost:80 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      #fill out your absolute path to your folder here
      # device: /absolute/path/to/web/template/folder
      # device: C:/Users/12407/Desktop/cmsc389T/cmsc389T-web-template
      device: C://Users//12407//Desktop//cmsc389T//cmsc389T-web-template
      o: bind

networks:
  app-network:
    driver: bridge 
